alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias ll='ls -la'
alias h='history'
alias v='vim'
alias gi='git init'
alias ga='git add .'
alias gc='git clone'
alias gcm='git commit -m'
alias gs='git status'
alias gps='git push'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gf='git fetch'
alias gms='git checkout master'
alias gmn='git checkout main'
alias gck='git checkout'
alias gcb='git checkout -b'
alias brew='HOMEBREW_NO_AUTO_UPDATE=1 brew'
alias pyenv-u='brew uninstall --ignore-dependencies openssl@1.1 && pyenv'
alias pyenv-i='brew uninstall --ignore-dependencies openssl@1.1'
alias g='cd ~/Workspace/github'
alias d='cd ~/Downloads'
alias c='code .'
alias restart='exec $SHELL'
alias gowasm='GOOS=js GOARCH=wasm go'
unalias gg

