alias ..='cd ..'
alias ...='cd ../../../'
alias ll='ls -la'
alias h='history'
alias v='vim'
alias gi='git init'
alias ga='git add .'
alias gc='git commit -m'
alias gs='git status'
alias gps='git push'
alias gpl='git pull'
alias brew='HOMEBREW_NO_AUTO_UPDATE=1 brew'
alias pyenv-u='brew uninstall --ignore-dependencies openssl@1.1 && pyenv'
alias pyenv-i='brew uninstall --ignore-dependencies openssl@1.1'
alias g='cd ~/Workspace/github'
